#spring.application.name=Ssave

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/dulumary
#spring.datasource.username=root
#spring.datasource.password=root
#
#mybatis.mapper-locations=mappers/*Mapper.xml

#spring.thymeleaf.cache=false


spring:
  application:
    name: Ssave
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssave
    username: root
    password: ${mysql.password}
    
    
mybatis:
  mapper-locations: mappers/*Mapper.xml
 
    

    

